---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-mcp
  namespace: demo-travel
  labels:
    app: weather-mcp
    component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-mcp
  template:
    metadata:
      labels:
        app: weather-mcp
        component: mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: weather-mcp
          image: 10.1.1.7:30500/demo-travel/weather-mcp:v0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: PORT
              value: "8001"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_SERVICE_NAME
              value: "weather-mcp-server"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
