---
apiVersion: v1
kind: Service
metadata:
  name: weather-mcp
  namespace: demo-travel
  labels:
    app: weather-mcp
spec:
  type: NodePort
  selector:
    app: weather-mcp
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30101
