apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag-service
          image: 10.1.1.7:30500/ai/rag-service:v0.1
          imagePullPolicy: Always
          env:
            - name: OLLAMA_URL
              value: "http://ollama:11434"
            - name: PG_HOST
              value: "postgres"
            - name: PG_DB
              value: "ragdb"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

