apiVersion: v1
kind: Endpoints
metadata:
  name: weather-mcp
  namespace: demo-travel
subsets:
  - addresses:
      - ip: 10.1.1.6
    ports:
      - port: 30101
---
apiVersion: v1
kind: Service
metadata:
  name: weather-mcp
  namespace: demo-travel
spec:
  ports:
    - port: 8001
      targetPort: 30101
