version: "3.9"

services:

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      PG_HOST: postgres
      PG_USER: travel
      PG_PASSWORD: travelpass
      PG_DB: travel
    ports:
      - "8080:5000"

volumes:
  postgres_data:

